spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

sentry:
  dsn: https://03c959934a22e937adcdb6fd8447601d@o4506263061856256.ingest.sentry.io/4506265617367040
  sentry.traces-sample-rate: 1.0
  environment: production
