base-url: /api

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://03c959934a22e937adcdb6fd8447601d@o4506263061856256.ingest.sentry.io/4506265617367040
  sentry.traces-sample-rate: 1.0
