base-url: /api

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem